// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvtej37UxBZaCxCyaseZVM4KJ7WBgMSGA',
    appId: '1:46960831159:web:46b6748cc7959ba446fb32',
    messagingSenderId: '46960831159',
    projectId: 'shop-app-8fcc6',
    authDomain: 'shop-app-8fcc6.firebaseapp.com',
    storageBucket: 'shop-app-8fcc6.firebasestorage.app',
    measurementId: 'G-HP1EMVY4R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2JVGMcsLyBwBRm4LCENo0o3mQ7EaGyc',
    appId: '1:46960831159:android:0f99cb0483a6009546fb32',
    messagingSenderId: '46960831159',
    projectId: 'shop-app-8fcc6',
    storageBucket: 'shop-app-8fcc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0VdKD-vuTCEDyyEAsjncjuzGQF0b3drE',
    appId: '1:46960831159:ios:f2c53abb97a975df46fb32',
    messagingSenderId: '46960831159',
    projectId: 'shop-app-8fcc6',
    storageBucket: 'shop-app-8fcc6.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );
}
